### ISSUE TITLE
You have wrong link on this repo in your npm page

### ISSUE THREAD

**Issue by nulltier** [bodhi-space/bodhi-dbf#1]
There, on page https://www.npmjs.com/package/bodhi-dbf, are written wrong url github.com/bodhi-space/dbf-parser

**Comment by tammerakrone** [comment]
Both links work.  Closing this issue.

**Comment by nulltier** [comment]
How it can works if your project have name bodhi-dbf when the links says dbf-parser and lead on 404 githubpage? I have copied this link from sidebar of the npm project page: https://github.com/bodhi-space/dbf-parser it does not work at all.

**Comment by dstockman** [comment]
Yep, it definitely looks like a wrong link in our npmjs info. We'll get it fixed shortly. In the meantime the right url is https://github.com/bodhi-space/bodhi-dbf 

Thanks @zonov for reporting this issue!
